site_name: Scarf Documentation
theme:
  name: material
  logo: assets/scarf_text.svg
  custom_dir: overrides
site_description: |
  Scarf's Technical Documentation & API Reference
extra_css:
  - "stylesheets/extra.css"
nav:
  - Introduction: "index.md"
  - Quick Start - Docker: "quick-start.md"
  - Quick Start - File Packages: "quick-start_file.md"
  - Scarf Gateway: "gateway.md"
  - SDKs for Package Authors: "package-analytics.md"
  - Documentation Insights: "web-traffic.md"
  - Organizations: "organization.md"
  - API: "api.md"
copyright: Copyright &copy; 2019 - 2022 Scarf Systems, Inc. <img referrerpolicy="no-referrer-when-downgrade" src="https://static.scarf.sh/a.png?x-pxid=c9065f3a-a090-4243-8f69-145d5de7bfca" />
google_analytics:
  - auto
  - G-GH3EXW7112
repo_url: https://github.com/scarf-sh/docs
markdown_extensions:
  - meta
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scarf-sh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/scarf_oss
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/scarf-sh
    - icon: fontawesome/brands/slack
      link: https://tinyurl.com/scarf-community-slack
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCiJRrlBKBOgYFRO9eb6pfdg
